name: Keploy CI

on: [push, pull_request]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Keploy
        run: |
          curl -sSfL https://keploy.io/install.sh -o keploy-install.sh
          chmod +x keploy-install.sh
          ./keploy-install.sh
          mv keploy /usr/local/bin/keploy

      - name: Record with Keploy
        run: |
          keploy record -c "npm run start" --delay 5 &
          sleep 10
          curl http://localhost:9090/api/posts
          sleep 5

      - name: Run Keploy Tests
        run: keploy test -c "npm run start"
