name: Keploy CI

on: [push, pull_request]

jobs:
  keploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start Keploy Record
        run: |
          curl -s https://raw.githubusercontent.com/keploy/keploy/main/install.sh | bash
          ./keploy record -c "npm start" --delay 5 &
          sleep 10
          curl http://localhost:3000/api/your-endpoint

      - name: Run Keploy Tests
        run: ./keploy test -c "npm start"
